package vista;

import controlador.PedidoControlador;

public class BienvenidaVista extends javax.swing.JFrame {
    private PedidoControlador controlador;  // importar controlador
    private TipoConsumoPagoVista tipoConsumoVista;

    public void setControlador(PedidoControlador ctrl) {
        this.controlador = ctrl;
    }
    
    public void setTipoConsumoPagoVista(TipoConsumoPagoVista vista) {
        this.tipoConsumoVista = vista;
    }

    public BienvenidaVista() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_ultima_capa = new javax.swing.JPanel();
        jl_img_bienvenida = new javax.swing.JLabel();
        jp_fondo_boton = new javax.swing.JPanel();
        jl_img_logo = new javax.swing.JLabel();
        jb_comenzar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jp_ultima_capa.setBackground(new java.awt.Color(242, 238, 228));
        jp_ultima_capa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_img_bienvenida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Bienvenida.png"))); // NOI18N
        jp_ultima_capa.add(jl_img_bienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 10, -1, 550));

        jp_fondo_boton.setBackground(new java.awt.Color(208, 29, 20));
        jp_fondo_boton.setLayout(null);

        jl_img_logo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jl_img_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/PizzaLabRojo.png"))); // NOI18N
        jp_fondo_boton.add(jl_img_logo);
        jl_img_logo.setBounds(30, 40, 100, 100);

        jb_comenzar.setBackground(new java.awt.Color(63, 108, 165));
        jb_comenzar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jb_comenzar.setForeground(new java.awt.Color(242, 238, 228));
        jb_comenzar.setText("                      Comenzar Orden");
        jb_comenzar.setBorder(null);
        jb_comenzar.setBorderPainted(false);
        jb_comenzar.setContentAreaFilled(false);
        jb_comenzar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb_comenzar.setFocusPainted(false);
        jb_comenzar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jb_comenzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_comenzarActionPerformed(evt);
            }
        });
        jp_fondo_boton.add(jb_comenzar);
        jb_comenzar.setBounds(0, 0, 411, 170);

        jp_ultima_capa.add(jp_fondo_boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 411, 170));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jp_ultima_capa, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jp_ultima_capa, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_comenzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_comenzarActionPerformed
        if (tipoConsumoVista != null) {
            tipoConsumoVista.setVisible(true);
            this.setVisible(false);
        } else {
            System.err.println("Error: tipoConsumoVista no ha sido asignada desde Main.");
        }
    }//GEN-LAST:event_jb_comenzarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jb_comenzar;
    private javax.swing.JLabel jl_img_bienvenida;
    private javax.swing.JLabel jl_img_logo;
    private javax.swing.JPanel jp_fondo_boton;
    private javax.swing.JPanel jp_ultima_capa;
    // End of variables declaration//GEN-END:variables
}
