package vista;

import controlador.CocinaObserver;
import controlador.PedidoControlador;
import java.awt.Font;
import servicio.Cocina;
import controlador.CocinaObserver;

public class CocinaVista extends javax.swing.JFrame implements CocinaObserver {
    private PedidoControlador controlador;  // importar controlador
    private InicioVista inicioVista;

    public void setControlador(PedidoControlador ctrl) {
        this.controlador = ctrl;
    }
    
    // Si necesitas una referencia a Cocina, agrega este método
    private Cocina cocina;
    public void setCocina(Cocina cocina) {
        this.cocina = cocina;
    }

    public CocinaVista() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        jp_pedidos_entregados.setVisible(false);
    }

    public void setInicioVista(InicioVista inicioVista) {
        this.inicioVista = inicioVista;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_fondo = new javax.swing.JPanel();
        jb_pedidos_entregados = new javax.swing.JButton();
        jb_pedidos_recibidos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jp_pedidos_entregados = new javax.swing.JPanel();
        jp_completado3 = new MyContainers.PanelRound();
        jl_entrega_completado3 = new javax.swing.JLabel();
        jl_bebida_completado3 = new javax.swing.JLabel();
        jl_ingredientes_completado3 = new javax.swing.JLabel();
        jl_masa_completado3 = new javax.swing.JLabel();
        jl_tamanio_completado3 = new javax.swing.JLabel();
        jl_tipo_completado3 = new javax.swing.JLabel();
        jl_cantidad_completado3 = new javax.swing.JLabel();
        jl_numero_completado3 = new javax.swing.JLabel();
        jl_estado_completado3 = new javax.swing.JLabel();
        jl_hora_completado3 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jp_completado2 = new MyContainers.PanelRound();
        jl_bebida_pedido9 = new javax.swing.JLabel();
        jl_bebida_pedido10 = new javax.swing.JLabel();
        jl_ingredientes_pedido5 = new javax.swing.JLabel();
        jl_masa_pedido5 = new javax.swing.JLabel();
        jl_tamanio_pedido5 = new javax.swing.JLabel();
        jl_tipo_pedido5 = new javax.swing.JLabel();
        jl_cantidad_pedido5 = new javax.swing.JLabel();
        jl_numero_pedido5 = new javax.swing.JLabel();
        jl_estado_pedido5 = new javax.swing.JLabel();
        jl_hora_pedido5 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jp_completado1 = new MyContainers.PanelRound();
        jl_bebida_pedido11 = new javax.swing.JLabel();
        jl_bebida_pedido12 = new javax.swing.JLabel();
        jl_ingredientes_pedido6 = new javax.swing.JLabel();
        jl_masa_pedido6 = new javax.swing.JLabel();
        jl_tamanio_pedido6 = new javax.swing.JLabel();
        jl_tipo_pedido6 = new javax.swing.JLabel();
        jl_cantidad_pedido6 = new javax.swing.JLabel();
        jl_numero_pedido6 = new javax.swing.JLabel();
        jl_estado_pedido6 = new javax.swing.JLabel();
        jl_hora_pedido6 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jp_pedidos_recibidos = new javax.swing.JPanel();
        jp_pedido3 = new MyContainers.PanelRound();
        jl_entrega_pedido3 = new javax.swing.JLabel();
        jl_bebida_pedido3 = new javax.swing.JLabel();
        jl_ingredientes_pedido3 = new javax.swing.JLabel();
        jl_masa_pedido3 = new javax.swing.JLabel();
        jl_tamanio_pedido3 = new javax.swing.JLabel();
        jl_tipo_pedido3 = new javax.swing.JLabel();
        jl_cantidad_pedido3 = new javax.swing.JLabel();
        jl_numero_pedido3 = new javax.swing.JLabel();
        jl_estado_pedido3 = new javax.swing.JLabel();
        jl_hora_pedido3 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jb_marcar_completado3 = new javax.swing.JButton();
        jp_personalizar_pizza2 = new MyContainers.PanelRound();
        jLabel35 = new javax.swing.JLabel();
        jp_pedido2 = new MyContainers.PanelRound();
        jl_entrega_pedido2 = new javax.swing.JLabel();
        jl_bebida_pedido2 = new javax.swing.JLabel();
        jl_ingredientes_pedido2 = new javax.swing.JLabel();
        jl_masa_pedido2 = new javax.swing.JLabel();
        jl_tamanio_pedido2 = new javax.swing.JLabel();
        jl_tipo_pedido2 = new javax.swing.JLabel();
        jl_cantidad_pedido2 = new javax.swing.JLabel();
        jl_numero_pedido2 = new javax.swing.JLabel();
        jl_estado_pedido2 = new javax.swing.JLabel();
        jl_hora_pedido2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jp_personalizar_pizza1 = new MyContainers.PanelRound();
        jb_marcar_completado2 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jp_pedido1 = new MyContainers.PanelRound();
        jl_entrega_pedido1 = new javax.swing.JLabel();
        jl_bebida_pedido1 = new javax.swing.JLabel();
        jl_ingredientes_pedido1 = new javax.swing.JLabel();
        jl_masa_pedido1 = new javax.swing.JLabel();
        jl_tamanio_pedido1 = new javax.swing.JLabel();
        jl_tipo_pedido1 = new javax.swing.JLabel();
        jl_cantidad_pedido1 = new javax.swing.JLabel();
        jl_numero_pedido1 = new javax.swing.JLabel();
        jl_estado_pedido1 = new javax.swing.JLabel();
        jl_hora_pedido1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jb_marcar_completado1 = new javax.swing.JButton();
        jp_personalizar_pizza = new MyContainers.PanelRound();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jp_fondo.setBackground(new java.awt.Color(208, 29, 20));
        jp_fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_pedidos_entregados.setBackground(new java.awt.Color(242, 229, 209));
        jb_pedidos_entregados.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jb_pedidos_entregados.setForeground(new java.awt.Color(242, 238, 228));
        jb_pedidos_entregados.setText("Pedidos Entregados");
        jb_pedidos_entregados.setBorder(null);
        jb_pedidos_entregados.setBorderPainted(false);
        jb_pedidos_entregados.setContentAreaFilled(false);
        jb_pedidos_entregados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb_pedidos_entregados.setFocusPainted(false);
        jb_pedidos_entregados.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jb_pedidos_entregados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_pedidos_entregadosActionPerformed(evt);
            }
        });
        jp_fondo.add(jb_pedidos_entregados, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, -1, -1));

        jb_pedidos_recibidos.setBackground(new java.awt.Color(242, 229, 209));
        jb_pedidos_recibidos.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jb_pedidos_recibidos.setForeground(new java.awt.Color(242, 238, 228));
        jb_pedidos_recibidos.setText("Pedidos Recibidos");
        jb_pedidos_recibidos.setBorder(null);
        jb_pedidos_recibidos.setBorderPainted(false);
        jb_pedidos_recibidos.setContentAreaFilled(false);
        jb_pedidos_recibidos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb_pedidos_recibidos.setFocusPainted(false);
        jb_pedidos_recibidos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jb_pedidos_recibidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_pedidos_recibidosActionPerformed(evt);
            }
        });
        jp_fondo.add(jb_pedidos_recibidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 180, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imgPizzaLab75x75.png"))); // NOI18N
        jp_fondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jp_pedidos_entregados.setBackground(new java.awt.Color(208, 29, 20));
        jp_pedidos_entregados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jp_completado3.setBackground(new java.awt.Color(242, 238, 228));
        jp_completado3.setRoundBottomLeft(20);
        jp_completado3.setRoundBottomRight(20);
        jp_completado3.setRoundTopLeft(20);
        jp_completado3.setRoundTopRight(20);
        jp_completado3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_entrega_completado3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_entrega_completado3.setForeground(new java.awt.Color(0, 0, 0));
        jl_entrega_completado3.setText("Local");
        jp_completado3.add(jl_entrega_completado3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 120, -1));

        jl_bebida_completado3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_bebida_completado3.setForeground(new java.awt.Color(0, 0, 0));
        jl_bebida_completado3.setText("Coca-Cola 500ml");
        jp_completado3.add(jl_bebida_completado3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 160, -1));

        jl_ingredientes_completado3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_ingredientes_completado3.setForeground(new java.awt.Color(0, 0, 0));
        jl_ingredientes_completado3.setText("Aceitunas");
        jp_completado3.add(jl_ingredientes_completado3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 100, -1));

        jl_masa_completado3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_masa_completado3.setForeground(new java.awt.Color(0, 0, 0));
        jl_masa_completado3.setText("Clasica");
        jp_completado3.add(jl_masa_completado3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 100, -1));

        jl_tamanio_completado3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_tamanio_completado3.setForeground(new java.awt.Color(0, 0, 0));
        jl_tamanio_completado3.setText("Grande");
        jp_completado3.add(jl_tamanio_completado3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 100, -1));

        jl_tipo_completado3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jl_tipo_completado3.setForeground(new java.awt.Color(0, 0, 0));
        jl_tipo_completado3.setText("Americana");
        jp_completado3.add(jl_tipo_completado3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 100, -1));

        jl_cantidad_completado3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_cantidad_completado3.setForeground(new java.awt.Color(0, 0, 0));
        jl_cantidad_completado3.setText("X");
        jp_completado3.add(jl_cantidad_completado3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 60, -1));

        jl_numero_completado3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jl_numero_completado3.setForeground(new java.awt.Color(0, 0, 0));
        jl_numero_completado3.setText("PED1750632857790");
        jp_completado3.add(jl_numero_completado3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 130, 30));

        jl_estado_completado3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_estado_completado3.setForeground(new java.awt.Color(0, 0, 0));
        jl_estado_completado3.setText("LISTO");
        jp_completado3.add(jl_estado_completado3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 70, -1));

        jl_hora_completado3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_hora_completado3.setForeground(new java.awt.Color(0, 0, 0));
        jl_hora_completado3.setText("XX:XX");
        jp_completado3.add(jl_hora_completado3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 60, -1));

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 0, 0));
        jLabel36.setText("Pedido: ");
        jp_completado3.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 0, 0));
        jLabel37.setText("#Pedido: ");
        jp_completado3.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel38.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 0, 0));
        jLabel38.setText("Hora:");
        jp_completado3.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 0, 0));
        jLabel39.setText("Entrega:");
        jp_completado3.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        jLabel40.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 0, 0));
        jLabel40.setText("Cantidad:");
        jp_completado3.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel41.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(0, 0, 0));
        jLabel41.setText("Detalles");
        jp_completado3.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 170, -1, -1));

        jLabel42.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(0, 0, 0));
        jLabel42.setText("Tamaño:");
        jp_completado3.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel43.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(0, 0, 0));
        jLabel43.setText("Masa:");
        jp_completado3.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel44.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(0, 0, 0));
        jLabel44.setText("Ingredientes:");
        jp_completado3.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel45.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(0, 0, 0));
        jLabel45.setText("Bebida");
        jp_completado3.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 290, -1, -1));

        jLabel46.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(0, 0, 0));
        jLabel46.setText("Estado:");
        jp_completado3.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jp_pedidos_entregados.add(jp_completado3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 240, 400));

        jp_completado2.setBackground(new java.awt.Color(242, 238, 228));
        jp_completado2.setRoundBottomLeft(20);
        jp_completado2.setRoundBottomRight(20);
        jp_completado2.setRoundTopLeft(20);
        jp_completado2.setRoundTopRight(20);
        jp_completado2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_bebida_pedido9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_bebida_pedido9.setForeground(new java.awt.Color(0, 0, 0));
        jl_bebida_pedido9.setText("LOCAL");
        jp_completado2.add(jl_bebida_pedido9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 120, -1));

        jl_bebida_pedido10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_bebida_pedido10.setForeground(new java.awt.Color(0, 0, 0));
        jl_bebida_pedido10.setText("----");
        jp_completado2.add(jl_bebida_pedido10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 160, -1));

        jl_ingredientes_pedido5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_ingredientes_pedido5.setForeground(new java.awt.Color(0, 0, 0));
        jl_ingredientes_pedido5.setText("Champiñones");
        jp_completado2.add(jl_ingredientes_pedido5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 100, -1));

        jl_masa_pedido5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_masa_pedido5.setForeground(new java.awt.Color(0, 0, 0));
        jl_masa_pedido5.setText("Clasica");
        jp_completado2.add(jl_masa_pedido5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 100, -1));

        jl_tamanio_pedido5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_tamanio_pedido5.setForeground(new java.awt.Color(0, 0, 0));
        jl_tamanio_pedido5.setText("Individual");
        jp_completado2.add(jl_tamanio_pedido5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 100, -1));

        jl_tipo_pedido5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jl_tipo_pedido5.setForeground(new java.awt.Color(0, 0, 0));
        jl_tipo_pedido5.setText("Margarita");
        jp_completado2.add(jl_tipo_pedido5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 70, -1));

        jl_cantidad_pedido5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_cantidad_pedido5.setForeground(new java.awt.Color(0, 0, 0));
        jl_cantidad_pedido5.setText("3");
        jp_completado2.add(jl_cantidad_pedido5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 60, -1));

        jl_numero_pedido5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jl_numero_pedido5.setForeground(new java.awt.Color(0, 0, 0));
        jl_numero_pedido5.setText("PED1750632857436");
        jp_completado2.add(jl_numero_pedido5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 130, 30));

        jl_estado_pedido5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_estado_pedido5.setForeground(new java.awt.Color(0, 0, 0));
        jl_estado_pedido5.setText("LISTO");
        jp_completado2.add(jl_estado_pedido5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 70, -1));

        jl_hora_pedido5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_hora_pedido5.setForeground(new java.awt.Color(0, 0, 0));
        jl_hora_pedido5.setText("11:46:12");
        jp_completado2.add(jl_hora_pedido5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 60, -1));

        jLabel47.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(0, 0, 0));
        jLabel47.setText("Pedido: ");
        jp_completado2.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel48.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(0, 0, 0));
        jLabel48.setText("#Pedido: ");
        jp_completado2.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel49.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(0, 0, 0));
        jLabel49.setText("Hora:");
        jp_completado2.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel50.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(0, 0, 0));
        jLabel50.setText("Entrega:");
        jp_completado2.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        jLabel51.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(0, 0, 0));
        jLabel51.setText("Cantidad:");
        jp_completado2.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel52.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(0, 0, 0));
        jLabel52.setText("Detalles");
        jp_completado2.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 170, -1, -1));

        jLabel53.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(0, 0, 0));
        jLabel53.setText("Tamaño:");
        jp_completado2.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel54.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(0, 0, 0));
        jLabel54.setText("Masa:");
        jp_completado2.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel55.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(0, 0, 0));
        jLabel55.setText("Ingredientes:");
        jp_completado2.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel56.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(0, 0, 0));
        jLabel56.setText("Bebida");
        jp_completado2.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 290, -1, -1));

        jLabel57.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(0, 0, 0));
        jLabel57.setText("Estado:");
        jp_completado2.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jp_pedidos_entregados.add(jp_completado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 10, 240, 400));

        jp_completado1.setBackground(new java.awt.Color(242, 238, 228));
        jp_completado1.setRoundBottomLeft(20);
        jp_completado1.setRoundBottomRight(20);
        jp_completado1.setRoundTopLeft(20);
        jp_completado1.setRoundTopRight(20);
        jp_completado1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_bebida_pedido11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_bebida_pedido11.setForeground(new java.awt.Color(0, 0, 0));
        jl_bebida_pedido11.setText("PARA LLEVAR");
        jp_completado1.add(jl_bebida_pedido11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 120, -1));

        jl_bebida_pedido12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_bebida_pedido12.setForeground(new java.awt.Color(0, 0, 0));
        jl_bebida_pedido12.setText("Pepsi 500ml");
        jp_completado1.add(jl_bebida_pedido12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 160, -1));

        jl_ingredientes_pedido6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_ingredientes_pedido6.setForeground(new java.awt.Color(0, 0, 0));
        jl_ingredientes_pedido6.setText("Jamón, Tomate");
        jp_completado1.add(jl_ingredientes_pedido6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 100, -1));

        jl_masa_pedido6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_masa_pedido6.setForeground(new java.awt.Color(0, 0, 0));
        jl_masa_pedido6.setText("Fina");
        jp_completado1.add(jl_masa_pedido6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 100, -1));

        jl_tamanio_pedido6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_tamanio_pedido6.setForeground(new java.awt.Color(0, 0, 0));
        jl_tamanio_pedido6.setText("Individual");
        jp_completado1.add(jl_tamanio_pedido6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 100, -1));

        jl_tipo_pedido6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jl_tipo_pedido6.setForeground(new java.awt.Color(0, 0, 0));
        jl_tipo_pedido6.setText("Mozzarella");
        jp_completado1.add(jl_tipo_pedido6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 120, -1));

        jl_cantidad_pedido6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_cantidad_pedido6.setForeground(new java.awt.Color(0, 0, 0));
        jl_cantidad_pedido6.setText("2");
        jp_completado1.add(jl_cantidad_pedido6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 60, -1));

        jl_numero_pedido6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jl_numero_pedido6.setForeground(new java.awt.Color(0, 0, 0));
        jl_numero_pedido6.setText("PED1750632857186");
        jp_completado1.add(jl_numero_pedido6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 120, 30));

        jl_estado_pedido6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_estado_pedido6.setForeground(new java.awt.Color(0, 0, 0));
        jl_estado_pedido6.setText("LISTO");
        jp_completado1.add(jl_estado_pedido6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 70, -1));

        jl_hora_pedido6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_hora_pedido6.setForeground(new java.awt.Color(0, 0, 0));
        jl_hora_pedido6.setText("11:46:56");
        jp_completado1.add(jl_hora_pedido6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 60, -1));

        jLabel58.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(0, 0, 0));
        jLabel58.setText("Pedido: ");
        jp_completado1.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel59.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(0, 0, 0));
        jLabel59.setText("#Pedido: ");
        jp_completado1.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel60.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(0, 0, 0));
        jLabel60.setText("Hora:");
        jp_completado1.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel61.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(0, 0, 0));
        jLabel61.setText("Entrega:");
        jp_completado1.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        jLabel62.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(0, 0, 0));
        jLabel62.setText("Cantidad:");
        jp_completado1.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel63.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(0, 0, 0));
        jLabel63.setText("Detalles");
        jp_completado1.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 170, -1, -1));

        jLabel64.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(0, 0, 0));
        jLabel64.setText("Tamaño:");
        jp_completado1.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel65.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(0, 0, 0));
        jLabel65.setText("Masa:");
        jp_completado1.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel66.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(0, 0, 0));
        jLabel66.setText("Ingredientes:");
        jp_completado1.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel67.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(0, 0, 0));
        jLabel67.setText("Bebida");
        jp_completado1.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 290, -1, -1));

        jLabel68.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(0, 0, 0));
        jLabel68.setText("Estado:");
        jp_completado1.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jp_pedidos_entregados.add(jp_completado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 400));

        jp_fondo.add(jp_pedidos_entregados, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 810, 420));

        jp_pedidos_recibidos.setBackground(new java.awt.Color(208, 29, 20));
        jp_pedidos_recibidos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jp_pedido3.setBackground(new java.awt.Color(242, 238, 228));
        jp_pedido3.setRoundBottomLeft(20);
        jp_pedido3.setRoundBottomRight(20);
        jp_pedido3.setRoundTopLeft(20);
        jp_pedido3.setRoundTopRight(20);
        jp_pedido3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_entrega_pedido3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_entrega_pedido3.setForeground(new java.awt.Color(0, 0, 0));
        jl_entrega_pedido3.setText("----");
        jp_pedido3.add(jl_entrega_pedido3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 120, -1));

        jl_bebida_pedido3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_bebida_pedido3.setForeground(new java.awt.Color(0, 0, 0));
        jl_bebida_pedido3.setText("----");
        jp_pedido3.add(jl_bebida_pedido3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 160, -1));

        jl_ingredientes_pedido3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_ingredientes_pedido3.setForeground(new java.awt.Color(0, 0, 0));
        jl_ingredientes_pedido3.setText("----");
        jp_pedido3.add(jl_ingredientes_pedido3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 100, -1));

        jl_masa_pedido3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_masa_pedido3.setForeground(new java.awt.Color(0, 0, 0));
        jl_masa_pedido3.setText("----");
        jp_pedido3.add(jl_masa_pedido3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 100, -1));

        jl_tamanio_pedido3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_tamanio_pedido3.setForeground(new java.awt.Color(0, 0, 0));
        jl_tamanio_pedido3.setText("----");
        jp_pedido3.add(jl_tamanio_pedido3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 100, -1));

        jl_tipo_pedido3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jl_tipo_pedido3.setForeground(new java.awt.Color(0, 0, 0));
        jl_tipo_pedido3.setText("----");
        jp_pedido3.add(jl_tipo_pedido3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 100, -1));

        jl_cantidad_pedido3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_cantidad_pedido3.setForeground(new java.awt.Color(0, 0, 0));
        jl_cantidad_pedido3.setText("----");
        jp_pedido3.add(jl_cantidad_pedido3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 60, -1));

        jl_numero_pedido3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jl_numero_pedido3.setForeground(new java.awt.Color(0, 0, 0));
        jl_numero_pedido3.setText("XXXXXX");
        jp_pedido3.add(jl_numero_pedido3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 130, 30));

        jl_estado_pedido3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_estado_pedido3.setForeground(new java.awt.Color(0, 0, 0));
        jl_estado_pedido3.setText("PENDIENTE");
        jp_pedido3.add(jl_estado_pedido3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 140, -1));

        jl_hora_pedido3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_hora_pedido3.setForeground(new java.awt.Color(0, 0, 0));
        jl_hora_pedido3.setText("----");
        jp_pedido3.add(jl_hora_pedido3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 140, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Pedido: ");
        jp_pedido3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("#Pedido: ");
        jp_pedido3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("Hora:");
        jp_pedido3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("Entrega:");
        jp_pedido3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("Cantidad:");
        jp_pedido3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("Detalles");
        jp_pedido3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 140, -1, -1));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 0));
        jLabel31.setText("Tamaño:");
        jp_pedido3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 0));
        jLabel32.setText("Masa:");
        jp_pedido3.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 0, 0));
        jLabel33.setText("Ingredientes:");
        jp_pedido3.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 0, 0));
        jLabel34.setText("Bebida");
        jp_pedido3.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 260, -1, -1));

        jb_marcar_completado3.setBackground(new java.awt.Color(242, 229, 209));
        jb_marcar_completado3.setForeground(new java.awt.Color(0, 0, 0));
        jb_marcar_completado3.setText("Marcar Completado");
        jb_marcar_completado3.setBorder(null);
        jb_marcar_completado3.setBorderPainted(false);
        jb_marcar_completado3.setContentAreaFilled(false);
        jb_marcar_completado3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb_marcar_completado3.setFocusPainted(false);
        jb_marcar_completado3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jb_marcar_completado3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_marcar_completado3ActionPerformed(evt);
            }
        });
        jp_pedido3.add(jb_marcar_completado3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 150, 30));

        jp_personalizar_pizza2.setBackground(new java.awt.Color(86, 212, 105));
        jp_personalizar_pizza2.setRoundBottomLeft(20);
        jp_personalizar_pizza2.setRoundBottomRight(20);
        jp_personalizar_pizza2.setRoundTopLeft(20);
        jp_personalizar_pizza2.setRoundTopRight(20);
        jp_personalizar_pizza2.setLayout(null);
        jp_pedido3.add(jp_personalizar_pizza2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 150, 30));

        jLabel35.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 0, 0));
        jLabel35.setText("Estado:");
        jp_pedido3.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jp_pedidos_recibidos.add(jp_pedido3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 240, 400));

        jp_pedido2.setBackground(new java.awt.Color(242, 238, 228));
        jp_pedido2.setRoundBottomLeft(20);
        jp_pedido2.setRoundBottomRight(20);
        jp_pedido2.setRoundTopLeft(20);
        jp_pedido2.setRoundTopRight(20);
        jp_pedido2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_entrega_pedido2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_entrega_pedido2.setForeground(new java.awt.Color(0, 0, 0));
        jl_entrega_pedido2.setText("PARA LLEVAR");
        jp_pedido2.add(jl_entrega_pedido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 120, -1));

        jl_bebida_pedido2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_bebida_pedido2.setForeground(new java.awt.Color(0, 0, 0));
        jl_bebida_pedido2.setText("Inca Kola 500ml");
        jp_pedido2.add(jl_bebida_pedido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 160, -1));

        jl_ingredientes_pedido2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_ingredientes_pedido2.setForeground(new java.awt.Color(0, 0, 0));
        jl_ingredientes_pedido2.setText("Tomate");
        jp_pedido2.add(jl_ingredientes_pedido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 100, -1));

        jl_masa_pedido2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_masa_pedido2.setForeground(new java.awt.Color(0, 0, 0));
        jl_masa_pedido2.setText("Clasica");
        jp_pedido2.add(jl_masa_pedido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 100, -1));

        jl_tamanio_pedido2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_tamanio_pedido2.setForeground(new java.awt.Color(0, 0, 0));
        jl_tamanio_pedido2.setText("Grande");
        jp_pedido2.add(jl_tamanio_pedido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 100, -1));

        jl_tipo_pedido2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jl_tipo_pedido2.setForeground(new java.awt.Color(0, 0, 0));
        jl_tipo_pedido2.setText("Americana");
        jp_pedido2.add(jl_tipo_pedido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 100, -1));

        jl_cantidad_pedido2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_cantidad_pedido2.setForeground(new java.awt.Color(0, 0, 0));
        jl_cantidad_pedido2.setText("2");
        jp_pedido2.add(jl_cantidad_pedido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 60, -1));

        jl_numero_pedido2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jl_numero_pedido2.setForeground(new java.awt.Color(0, 0, 0));
        jl_numero_pedido2.setText("PED175063294342");
        jp_pedido2.add(jl_numero_pedido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 130, 30));

        jl_estado_pedido2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_estado_pedido2.setForeground(new java.awt.Color(0, 0, 0));
        jl_estado_pedido2.setText("PENDIENTE");
        jp_pedido2.add(jl_estado_pedido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 110, -1));

        jl_hora_pedido2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_hora_pedido2.setForeground(new java.awt.Color(0, 0, 0));
        jl_hora_pedido2.setText("11:51");
        jp_pedido2.add(jl_hora_pedido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 60, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Pedido: ");
        jp_pedido2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("#Pedido: ");
        jp_pedido2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Hora:");
        jp_pedido2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Entrega:");
        jp_pedido2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Cantidad:");
        jp_pedido2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Detalles");
        jp_pedido2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 140, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Tamaño:");
        jp_pedido2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Masa:");
        jp_pedido2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Ingredientes:");
        jp_pedido2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Bebida");
        jp_pedido2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 260, -1, -1));

        jp_personalizar_pizza1.setBackground(new java.awt.Color(86, 212, 105));
        jp_personalizar_pizza1.setRoundBottomLeft(20);
        jp_personalizar_pizza1.setRoundBottomRight(20);
        jp_personalizar_pizza1.setRoundTopLeft(20);
        jp_personalizar_pizza1.setRoundTopRight(20);
        jp_personalizar_pizza1.setLayout(null);

        jb_marcar_completado2.setBackground(new java.awt.Color(242, 229, 209));
        jb_marcar_completado2.setForeground(new java.awt.Color(0, 0, 0));
        jb_marcar_completado2.setText("Marcar Completado");
        jb_marcar_completado2.setBorder(null);
        jb_marcar_completado2.setBorderPainted(false);
        jb_marcar_completado2.setContentAreaFilled(false);
        jb_marcar_completado2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb_marcar_completado2.setFocusPainted(false);
        jb_marcar_completado2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jb_marcar_completado2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_marcar_completado2ActionPerformed(evt);
            }
        });
        jp_personalizar_pizza1.add(jb_marcar_completado2);
        jb_marcar_completado2.setBounds(0, 0, 150, 30);

        jp_pedido2.add(jp_personalizar_pizza1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 150, 30));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Estado:");
        jp_pedido2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jp_pedidos_recibidos.add(jp_pedido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 10, 240, 400));

        jp_pedido1.setBackground(new java.awt.Color(242, 238, 228));
        jp_pedido1.setRoundBottomLeft(20);
        jp_pedido1.setRoundBottomRight(20);
        jp_pedido1.setRoundTopLeft(20);
        jp_pedido1.setRoundTopRight(20);
        jp_pedido1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_entrega_pedido1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_entrega_pedido1.setForeground(new java.awt.Color(0, 0, 0));
        jl_entrega_pedido1.setText("PARA LLEVAR");
        jp_pedido1.add(jl_entrega_pedido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 120, -1));

        jl_bebida_pedido1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_bebida_pedido1.setForeground(new java.awt.Color(0, 0, 0));
        jl_bebida_pedido1.setText("Coca-Cola 500ml");
        jp_pedido1.add(jl_bebida_pedido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 160, -1));

        jl_ingredientes_pedido1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_ingredientes_pedido1.setForeground(new java.awt.Color(0, 0, 0));
        jl_ingredientes_pedido1.setText("Aceitunas");
        jp_pedido1.add(jl_ingredientes_pedido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 100, -1));

        jl_masa_pedido1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_masa_pedido1.setForeground(new java.awt.Color(0, 0, 0));
        jl_masa_pedido1.setText("Fina");
        jp_pedido1.add(jl_masa_pedido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 100, -1));

        jl_tamanio_pedido1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_tamanio_pedido1.setForeground(new java.awt.Color(0, 0, 0));
        jl_tamanio_pedido1.setText("Individual");
        jp_pedido1.add(jl_tamanio_pedido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 100, -1));

        jl_tipo_pedido1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jl_tipo_pedido1.setForeground(new java.awt.Color(0, 0, 0));
        jl_tipo_pedido1.setText("Personalizada");
        jp_pedido1.add(jl_tipo_pedido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 140, -1));

        jl_cantidad_pedido1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_cantidad_pedido1.setForeground(new java.awt.Color(0, 0, 0));
        jl_cantidad_pedido1.setText("1");
        jp_pedido1.add(jl_cantidad_pedido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 60, -1));

        jl_numero_pedido1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jl_numero_pedido1.setForeground(new java.awt.Color(0, 0, 0));
        jl_numero_pedido1.setText("PED1750632947186");
        jp_pedido1.add(jl_numero_pedido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 120, 30));

        jl_estado_pedido1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_estado_pedido1.setForeground(new java.awt.Color(0, 0, 0));
        jl_estado_pedido1.setText("PENDIENTE");
        jp_pedido1.add(jl_estado_pedido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 100, -1));

        jl_hora_pedido1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_hora_pedido1.setForeground(new java.awt.Color(0, 0, 0));
        jl_hora_pedido1.setText("11:50");
        jp_pedido1.add(jl_hora_pedido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 60, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Pedido: ");
        jp_pedido1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("#Pedido: ");
        jp_pedido1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Hora:");
        jp_pedido1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Entrega:");
        jp_pedido1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Cantidad:");
        jp_pedido1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Detalles");
        jp_pedido1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 140, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Tamaño:");
        jp_pedido1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Masa:");
        jp_pedido1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Ingredientes:");
        jp_pedido1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Bebida");
        jp_pedido1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 260, -1, -1));

        jb_marcar_completado1.setBackground(new java.awt.Color(242, 229, 209));
        jb_marcar_completado1.setForeground(new java.awt.Color(0, 0, 0));
        jb_marcar_completado1.setText("Marcar Completado");
        jb_marcar_completado1.setBorder(null);
        jb_marcar_completado1.setBorderPainted(false);
        jb_marcar_completado1.setContentAreaFilled(false);
        jb_marcar_completado1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb_marcar_completado1.setFocusPainted(false);
        jb_marcar_completado1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jb_marcar_completado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_marcar_completado1ActionPerformed(evt);
            }
        });
        jp_pedido1.add(jb_marcar_completado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 150, 30));

        jp_personalizar_pizza.setBackground(new java.awt.Color(86, 212, 105));
        jp_personalizar_pizza.setRoundBottomLeft(20);
        jp_personalizar_pizza.setRoundBottomRight(20);
        jp_personalizar_pizza.setRoundTopLeft(20);
        jp_personalizar_pizza.setRoundTopRight(20);
        jp_personalizar_pizza.setLayout(null);
        jp_pedido1.add(jp_personalizar_pizza, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 150, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Estado:");
        jp_pedido1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jp_pedidos_recibidos.add(jp_pedido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 400));

        jp_fondo.add(jp_pedidos_recibidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 810, 420));

        jPanel2.setBackground(new java.awt.Color(208, 29, 20));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        jp_fondo.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, 30, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_pedidos_recibidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_pedidos_recibidosActionPerformed
        jp_pedidos_entregados.setVisible(false);
        jb_pedidos_entregados.setFont(jb_pedidos_entregados.getFont().deriveFont(Font.PLAIN));
        
        jp_pedidos_recibidos.setVisible(true);
        jb_pedidos_recibidos.setFont(jb_pedidos_recibidos.getFont().deriveFont(Font.BOLD));
    }//GEN-LAST:event_jb_pedidos_recibidosActionPerformed

    private void jb_pedidos_entregadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_pedidos_entregadosActionPerformed
        jp_pedidos_recibidos.setVisible(false);
        jb_pedidos_recibidos.setFont(jb_pedidos_recibidos.getFont().deriveFont(Font.PLAIN));
        
        jp_pedidos_entregados.setVisible(true);
        jb_pedidos_entregados.setFont(jb_pedidos_entregados.getFont().deriveFont(Font.BOLD));
    }//GEN-LAST:event_jb_pedidos_entregadosActionPerformed

    private void jb_marcar_completado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_marcar_completado1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_marcar_completado1ActionPerformed
    
    
    private void jb_marcar_completado3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_marcar_completado3ActionPerformed
        if (controlador != null) {
            controlador.marcarPedidoListo(jl_numero_pedido3.getText());
        }
        // La vista se actualizará vía observer cuando el modelo cambie
    }//GEN-LAST:event_jb_marcar_completado3ActionPerformed

    private void jb_marcar_completado2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_marcar_completado2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_marcar_completado2ActionPerformed
// Muestra los datos del pedido en los labels del panel jp_pedido3
public void mostrarNuevoPedido(modelo.Pedido pedido) {
    // Mostrar datos básicos del pedido
    jl_numero_pedido3.setText(pedido.getId());
    jl_hora_pedido3.setText(pedido.getFechaHora().toLocalTime().toString());
    jl_estado_pedido3.setText(pedido.getEstado());
    jl_tipo_pedido3.setText(pedido.getNombrePizza());

    // Mostrar cantidad: si viene de InicioVista, úsala; si no, usa la del objeto Pedido
    if (inicioVista != null) {
        jl_cantidad_pedido3.setText(inicioVista.getCantidadSeleccionada());
    } else {
        jl_cantidad_pedido3.setText(String.valueOf(pedido.getCantidad()));
    }

    // Mostrar tamaño y masa
    jl_tamanio_pedido3.setText(pedido.getTamanio());
    jl_masa_pedido3.setText(pedido.getMasa());

    // Mostrar ingredientes
    jl_ingredientes_pedido3.setText(ingredientesToString(pedido.getIngredientes()));

    // Mostrar bebida (si la tienes implementada como ingrediente tipo bebida)
    jl_bebida_pedido3.setText(extraerBebidas(pedido.getIngredientes()));

    // Mostrar tipo de consumo (local / para llevar)
    jl_entrega_pedido3.setText(pedido.getTipoConsumo());

    // Mostrar el panel del pedido
    jp_pedido3.setVisible(true);
}
    // Muestra una alerta (puedes usar JOptionPane o un label especial)
    public void mostrarAlerta(String mensaje) {
        javax.swing.JOptionPane.showMessageDialog(this, mensaje, "Alerta", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }

    // Cuando se marca como completado, pasa la info a jp_completado3 y oculta jp_pedido3
    public void marcarPedidoComoListo(String idPedido) {
        jl_numero_completado3.setText(jl_numero_pedido3.getText());
        jl_hora_completado3.setText(jl_hora_pedido3.getText());
        jl_estado_completado3.setText("LISTO");
        jl_tipo_completado3.setText(jl_tipo_pedido3.getText());
        jl_cantidad_completado3.setText(jl_cantidad_pedido3.getText());
        jl_tamanio_completado3.setText(jl_tamanio_pedido3.getText());
        jl_masa_completado3.setText(jl_masa_pedido3.getText());
        jl_ingredientes_completado3.setText(jl_ingredientes_pedido3.getText());
        jl_bebida_completado3.setText(jl_bebida_pedido3.getText());
        jl_entrega_completado3.setText(jl_entrega_pedido3.getText());
        jp_pedido3.setVisible(false);
        jp_completado3.setVisible(true);
    }

    /**
     * Actualiza la UI para mover el pedido de pendiente a completado.
     */
    public void pedidoCompletado(String idPedido) {
        // Aquí deberías buscar el panel del pedido pendiente por idPedido,
        // removerlo del panel de pendientes y agregarlo al panel de completados.
        // Ejemplo básico (ajusta según tu implementación real):
        moverPedidoAPanelCompletado(idPedido);
    }

    private void moverPedidoAPanelCompletado(String idPedido) {
        // Ejemplo: si el idPedido corresponde a jp_pedido3
        if (jp_pedido3 != null && jl_numero_pedido3.getText().equals(idPedido)) {
            jp_pedidos_recibidos.remove(jp_pedido3);
            jp_pedidos_recibidos.revalidate();
            jp_pedidos_recibidos.repaint();
            jp_pedidos_entregados.add(jp_pedido3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 240, 400));
            jp_pedidos_entregados.revalidate();
            jp_pedidos_entregados.repaint();
        }
    }

    private String ingredientesToString(java.util.List<modelo.Ingrediente> ingredientes) {
        if (ingredientes == null || ingredientes.isEmpty()) return "-";
        StringBuilder sb = new StringBuilder();
        for (modelo.Ingrediente ing : ingredientes) {
            if (!esBebida(ing)) {
                sb.append(ing.getNombre()).append(", ");
            }
        }
        if (sb.length() > 2) sb.setLength(sb.length() - 2); // Quita la última coma
        return sb.toString();
    }

    private String extraerBebidas(java.util.List<modelo.Ingrediente> ingredientes) {
        if (ingredientes == null) return "-";
        StringBuilder sb = new StringBuilder();
        for (modelo.Ingrediente ing : ingredientes) {
            if (esBebida(ing)) {
                sb.append(ing.getNombre()).append(", ");
            }
        }
        if (sb.length() > 2) sb.setLength(sb.length() - 2);
        return sb.length() > 0 ? sb.toString() : "-";
    }

    private boolean esBebida(modelo.Ingrediente ing) {
        String nombre = ing.getNombre().toLowerCase();
        return nombre.contains("coca") || nombre.contains("pepsi") || nombre.contains("inca") || nombre.contains("sprite");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jb_marcar_completado1;
    private javax.swing.JButton jb_marcar_completado2;
    private javax.swing.JButton jb_marcar_completado3;
    private javax.swing.JButton jb_pedidos_entregados;
    private javax.swing.JButton jb_pedidos_recibidos;
    private javax.swing.JLabel jl_bebida_completado3;
    private javax.swing.JLabel jl_bebida_pedido1;
    private javax.swing.JLabel jl_bebida_pedido10;
    private javax.swing.JLabel jl_bebida_pedido11;
    private javax.swing.JLabel jl_bebida_pedido12;
    private javax.swing.JLabel jl_bebida_pedido2;
    private javax.swing.JLabel jl_bebida_pedido3;
    private javax.swing.JLabel jl_bebida_pedido9;
    private javax.swing.JLabel jl_cantidad_completado3;
    private javax.swing.JLabel jl_cantidad_pedido1;
    private javax.swing.JLabel jl_cantidad_pedido2;
    private javax.swing.JLabel jl_cantidad_pedido3;
    private javax.swing.JLabel jl_cantidad_pedido5;
    private javax.swing.JLabel jl_cantidad_pedido6;
    private javax.swing.JLabel jl_entrega_completado3;
    private javax.swing.JLabel jl_entrega_pedido1;
    private javax.swing.JLabel jl_entrega_pedido2;
    private javax.swing.JLabel jl_entrega_pedido3;
    private javax.swing.JLabel jl_estado_completado3;
    private javax.swing.JLabel jl_estado_pedido1;
    private javax.swing.JLabel jl_estado_pedido2;
    private javax.swing.JLabel jl_estado_pedido3;
    private javax.swing.JLabel jl_estado_pedido5;
    private javax.swing.JLabel jl_estado_pedido6;
    private javax.swing.JLabel jl_hora_completado3;
    private javax.swing.JLabel jl_hora_pedido1;
    private javax.swing.JLabel jl_hora_pedido2;
    private javax.swing.JLabel jl_hora_pedido3;
    private javax.swing.JLabel jl_hora_pedido5;
    private javax.swing.JLabel jl_hora_pedido6;
    private javax.swing.JLabel jl_ingredientes_completado3;
    private javax.swing.JLabel jl_ingredientes_pedido1;
    private javax.swing.JLabel jl_ingredientes_pedido2;
    private javax.swing.JLabel jl_ingredientes_pedido3;
    private javax.swing.JLabel jl_ingredientes_pedido5;
    private javax.swing.JLabel jl_ingredientes_pedido6;
    private javax.swing.JLabel jl_masa_completado3;
    private javax.swing.JLabel jl_masa_pedido1;
    private javax.swing.JLabel jl_masa_pedido2;
    private javax.swing.JLabel jl_masa_pedido3;
    private javax.swing.JLabel jl_masa_pedido5;
    private javax.swing.JLabel jl_masa_pedido6;
    private javax.swing.JLabel jl_numero_completado3;
    private javax.swing.JLabel jl_numero_pedido1;
    private javax.swing.JLabel jl_numero_pedido2;
    private javax.swing.JLabel jl_numero_pedido3;
    private javax.swing.JLabel jl_numero_pedido5;
    private javax.swing.JLabel jl_numero_pedido6;
    private javax.swing.JLabel jl_tamanio_completado3;
    private javax.swing.JLabel jl_tamanio_pedido1;
    private javax.swing.JLabel jl_tamanio_pedido2;
    private javax.swing.JLabel jl_tamanio_pedido3;
    private javax.swing.JLabel jl_tamanio_pedido5;
    private javax.swing.JLabel jl_tamanio_pedido6;
    private javax.swing.JLabel jl_tipo_completado3;
    private javax.swing.JLabel jl_tipo_pedido1;
    private javax.swing.JLabel jl_tipo_pedido2;
    private javax.swing.JLabel jl_tipo_pedido3;
    private javax.swing.JLabel jl_tipo_pedido5;
    private javax.swing.JLabel jl_tipo_pedido6;
    private MyContainers.PanelRound jp_completado1;
    private MyContainers.PanelRound jp_completado2;
    private MyContainers.PanelRound jp_completado3;
    private javax.swing.JPanel jp_fondo;
    private MyContainers.PanelRound jp_pedido1;
    private MyContainers.PanelRound jp_pedido2;
    private MyContainers.PanelRound jp_pedido3;
    private javax.swing.JPanel jp_pedidos_entregados;
    private javax.swing.JPanel jp_pedidos_recibidos;
    private MyContainers.PanelRound jp_personalizar_pizza;
    private MyContainers.PanelRound jp_personalizar_pizza1;
    private MyContainers.PanelRound jp_personalizar_pizza2;
    // End of variables declaration//GEN-END:variables
}
