package vista;

import controlador.PedidoControlador;

public class EmergentesVista extends javax.swing.JFrame {
    InicioVista ventanaInicio;
    private PedidoControlador controlador;  // importar controlador

    public void setControlador(PedidoControlador ctrl) {
        this.controlador = ctrl;
    }
    
    public EmergentesVista(String ventana, InicioVista inicio) {
        this.ventanaInicio = inicio;
        
        if(ventana.contentEquals("jp_pregunta_personalizar")){
            initComponents();
            this.setLocationRelativeTo(null);
            
            // Mostrar ventana de pregunta
            jp_producto_agregado.setVisible(false);
            jp_pregunta_personalizar.setVisible(true);
        } else if (ventana.contentEquals("jp_producto_agregado")){
            initComponents();
            this.setLocationRelativeTo(null);
            
            // Mostrar ventana de confirmacion agregado
            jp_pregunta_personalizar.setVisible(false);
            jp_producto_agregado.setVisible(true);
        } else{
            initComponents();
            this.setLocationRelativeTo(null);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_ultima_capa = new javax.swing.JPanel();
        jp_pregunta_personalizar = new javax.swing.JPanel();
        jl_img_personalizacion = new javax.swing.JLabel();
        jp_cancelar_pedido = new MyContainers.PanelRound();
        jb_cancelar_pedido = new javax.swing.JButton();
        jp_personalizar_pizza = new MyContainers.PanelRound();
        jb_agregar_pedido = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jp_producto_agregado = new javax.swing.JPanel();
        jl_img_confirmacion = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jp_ultima_capa.setBackground(new java.awt.Color(242, 238, 228));
        jp_ultima_capa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jp_pregunta_personalizar.setBackground(new java.awt.Color(242, 238, 228));
        jp_pregunta_personalizar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_img_personalizacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/crearPizza160x160.png"))); // NOI18N
        jp_pregunta_personalizar.add(jl_img_personalizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 250, 160, 160));

        jp_cancelar_pedido.setBackground(new java.awt.Color(204, 204, 204));
        jp_cancelar_pedido.setRoundBottomLeft(20);
        jp_cancelar_pedido.setRoundBottomRight(20);
        jp_cancelar_pedido.setRoundTopLeft(20);
        jp_cancelar_pedido.setRoundTopRight(20);
        jp_cancelar_pedido.setLayout(null);

        jb_cancelar_pedido.setBackground(new java.awt.Color(242, 229, 209));
        jb_cancelar_pedido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jb_cancelar_pedido.setForeground(new java.awt.Color(0, 0, 0));
        jb_cancelar_pedido.setText("No, gracias.");
        jb_cancelar_pedido.setBorder(null);
        jb_cancelar_pedido.setBorderPainted(false);
        jb_cancelar_pedido.setContentAreaFilled(false);
        jb_cancelar_pedido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb_cancelar_pedido.setFocusPainted(false);
        jb_cancelar_pedido.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jb_cancelar_pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cancelar_pedidoActionPerformed(evt);
            }
        });
        jp_cancelar_pedido.add(jb_cancelar_pedido);
        jb_cancelar_pedido.setBounds(0, 0, 230, 50);

        jp_pregunta_personalizar.add(jp_cancelar_pedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 620, 230, 50));

        jp_personalizar_pizza.setBackground(new java.awt.Color(86, 212, 105));
        jp_personalizar_pizza.setRoundBottomLeft(20);
        jp_personalizar_pizza.setRoundBottomRight(20);
        jp_personalizar_pizza.setRoundTopLeft(20);
        jp_personalizar_pizza.setRoundTopRight(20);
        jp_personalizar_pizza.setLayout(null);

        jb_agregar_pedido.setBackground(new java.awt.Color(242, 229, 209));
        jb_agregar_pedido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jb_agregar_pedido.setForeground(new java.awt.Color(0, 0, 0));
        jb_agregar_pedido.setText("Si, quiero personalizarla");
        jb_agregar_pedido.setBorder(null);
        jb_agregar_pedido.setBorderPainted(false);
        jb_agregar_pedido.setContentAreaFilled(false);
        jb_agregar_pedido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb_agregar_pedido.setFocusPainted(false);
        jb_agregar_pedido.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jb_agregar_pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_agregar_pedidoActionPerformed(evt);
            }
        });
        jp_personalizar_pizza.add(jb_agregar_pedido);
        jb_agregar_pedido.setBounds(0, 0, 230, 50);

        jp_pregunta_personalizar.add(jp_personalizar_pizza, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 540, 230, 50));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("tu pizza?");
        jp_pregunta_personalizar.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 110, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("¿Deseas personalizar");
        jp_pregunta_personalizar.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 250, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("crea tu propia mezcla.");
        jp_pregunta_personalizar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 470, 140, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Agrega ingredientes, ");
        jp_pregunta_personalizar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, 140, -1));

        jp_ultima_capa.add(jp_pregunta_personalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 730));

        jp_producto_agregado.setBackground(new java.awt.Color(242, 238, 228));
        jp_producto_agregado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_img_confirmacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/productoAñadido180x177.png"))); // NOI18N
        jp_producto_agregado.add(jl_img_confirmacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 160, 160));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("El total de tu pedido ha sido actualizado");
        jp_producto_agregado.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 480, 270, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Producto Añadido");
        jp_producto_agregado.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 210, -1));

        jp_ultima_capa.add(jp_producto_agregado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 730));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jp_ultima_capa, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jp_ultima_capa, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_agregar_pedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_agregar_pedidoActionPerformed
        this.setVisible(false);
        ventanaInicio.setVisible(true);
    }//GEN-LAST:event_jb_agregar_pedidoActionPerformed

    private void jb_cancelar_pedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cancelar_pedidoActionPerformed
        this.setVisible(false);
        ventanaInicio.mostrarResumenPedido();
        ventanaInicio.setVisible(true);
    }//GEN-LAST:event_jb_cancelar_pedidoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton jb_agregar_pedido;
    private javax.swing.JButton jb_cancelar_pedido;
    private javax.swing.JLabel jl_img_confirmacion;
    private javax.swing.JLabel jl_img_personalizacion;
    private MyContainers.PanelRound jp_cancelar_pedido;
    private MyContainers.PanelRound jp_personalizar_pizza;
    private javax.swing.JPanel jp_pregunta_personalizar;
    private javax.swing.JPanel jp_producto_agregado;
    private javax.swing.JPanel jp_ultima_capa;
    // End of variables declaration//GEN-END:variables
}
