package vista;

import controlador.PedidoControlador;
import java.awt.event.ActionListener;
import javax.swing.JButton;

public class ProcesoPagoVista extends javax.swing.JFrame {
    private PedidoControlador controlador;  // importar controlador

    public void setControlador(PedidoControlador ctrl) {
        this.controlador = ctrl;
    }
    
    private boolean boleta = false;
    private boolean factura = false;


    public ProcesoPagoVista() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        //Ocultar el pedido de ruc o dni
        jp_pedir_ruc.setVisible(false);
        jp_pedir_dni.setVisible(false);
        jp_numeros.setVisible(false);
        jp_mensaje_tarjeta.setVisible(false);
        jp_mensaje_billetera_digital.setVisible(false);
        jp_mensaje_confirmacion.setVisible(false);
        
        // Listener que toma el texto del botón y lo añade al campo
        ActionListener numeroListener = evt -> {
            JButton src = (JButton) evt.getSource();
            agregarDigitoCampoActivo(src.getText());
        };
        
        // Asignas el mismo listener a todos tus botones numéricos
        jb_numero0.addActionListener(numeroListener);
        jb_numero1.addActionListener(numeroListener);
        jb_numero2.addActionListener(numeroListener);
        jb_numero3.addActionListener(numeroListener);
        jb_numero4.addActionListener(numeroListener);
        jb_numero5.addActionListener(numeroListener);
        jb_numero6.addActionListener(numeroListener);
        jb_numero7.addActionListener(numeroListener);
        jb_numero8.addActionListener(numeroListener);
        jb_numero9.addActionListener(numeroListener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_ultima_capa = new javax.swing.JPanel();
        jl_logo_empresa = new javax.swing.JLabel();
        jp_numeros = new javax.swing.JPanel();
        jp_confirmar = new MyContainers.PanelRound();
        jb_confirmar = new javax.swing.JButton();
        jp_eliminar = new MyContainers.PanelRound();
        jb_eliminar = new javax.swing.JButton();
        jp_numero0 = new MyContainers.PanelRound();
        jb_numero0 = new javax.swing.JButton();
        jp_numero9 = new MyContainers.PanelRound();
        jb_numero9 = new javax.swing.JButton();
        jp_numero8 = new MyContainers.PanelRound();
        jb_numero8 = new javax.swing.JButton();
        jp_numero7 = new MyContainers.PanelRound();
        jb_numero7 = new javax.swing.JButton();
        jp_numero6 = new MyContainers.PanelRound();
        jb_numero6 = new javax.swing.JButton();
        jp_numero5 = new MyContainers.PanelRound();
        jb_numero5 = new javax.swing.JButton();
        jp_numero4 = new MyContainers.PanelRound();
        jb_numero4 = new javax.swing.JButton();
        jp_numero3 = new MyContainers.PanelRound();
        jb_numero3 = new javax.swing.JButton();
        jp_numero2 = new MyContainers.PanelRound();
        jb_numero2 = new javax.swing.JButton();
        jp_numero1 = new MyContainers.PanelRound();
        jb_numero1 = new javax.swing.JButton();
        jp_pedir_dni = new javax.swing.JPanel();
        jp_fondo_numeroDNI = new MyContainers.PanelRound();
        txtNumeroDNI = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jp_pedir_ruc = new javax.swing.JPanel();
        jp_fondo_numeroRUC = new MyContainers.PanelRound();
        txtNumeroRUC = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jp_boleta_factura = new javax.swing.JPanel();
        jp_boleta = new MyContainers.PanelRound();
        jb_boleta = new javax.swing.JButton();
        jp_factura = new MyContainers.PanelRound();
        jb_factura = new javax.swing.JButton();
        jp_mensaje_tarjeta = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jl_pos = new javax.swing.JLabel();
        jp_mensaje_billetera_digital = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jl_pos1 = new javax.swing.JLabel();
        jp_mensaje_confirmacion = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jl_pos2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jp_ultima_capa.setBackground(new java.awt.Color(208, 29, 20));
        jp_ultima_capa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_logo_empresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoPizzaLabGrande200x200.png"))); // NOI18N
        jp_ultima_capa.add(jl_logo_empresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 120, 190, 170));

        jp_numeros.setBackground(new java.awt.Color(208, 29, 20));
        jp_numeros.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jp_confirmar.setBackground(new java.awt.Color(86, 212, 105));
        jp_confirmar.setRoundBottomLeft(20);
        jp_confirmar.setRoundBottomRight(20);
        jp_confirmar.setRoundTopLeft(20);
        jp_confirmar.setRoundTopRight(20);
        jp_confirmar.setLayout(null);

        jb_confirmar.setBackground(new java.awt.Color(86, 212, 105));
        jb_confirmar.setForeground(new java.awt.Color(242, 238, 228));
        jb_confirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/check30x30.png"))); // NOI18N
        jb_confirmar.setText("");
        jb_confirmar.setBorder(null);
        jb_confirmar.setBorderPainted(false);
        jb_confirmar.setContentAreaFilled(false);
        jb_confirmar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb_confirmar.setFocusPainted(false);
        jb_confirmar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jb_confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_confirmarActionPerformed(evt);
            }
        });
        jp_confirmar.add(jb_confirmar);
        jb_confirmar.setBounds(0, 0, 110, 50);

        jp_numeros.add(jp_confirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 110, 50));

        jp_eliminar.setBackground(new java.awt.Color(242, 238, 228));
        jp_eliminar.setRoundBottomLeft(20);
        jp_eliminar.setRoundBottomRight(20);
        jp_eliminar.setRoundTopLeft(20);
        jp_eliminar.setRoundTopRight(20);
        jp_eliminar.setLayout(null);

        jb_eliminar.setBackground(new java.awt.Color(242, 238, 228));
        jb_eliminar.setForeground(new java.awt.Color(242, 238, 228));
        jb_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar30x30.png"))); // NOI18N
        jb_eliminar.setText("");
        jb_eliminar.setBorder(null);
        jb_eliminar.setBorderPainted(false);
        jb_eliminar.setContentAreaFilled(false);
        jb_eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb_eliminar.setFocusPainted(false);
        jb_eliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jb_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_eliminarActionPerformed(evt);
            }
        });
        jp_eliminar.add(jb_eliminar);
        jb_eliminar.setBounds(0, 0, 110, 50);

        jp_numeros.add(jp_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 110, 50));

        jp_numero0.setBackground(new java.awt.Color(242, 238, 228));
        jp_numero0.setRoundBottomLeft(20);
        jp_numero0.setRoundBottomRight(20);
        jp_numero0.setRoundTopLeft(20);
        jp_numero0.setRoundTopRight(20);
        jp_numero0.setLayout(null);

        jb_numero0.setBackground(new java.awt.Color(242, 238, 228));
        jb_numero0.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jb_numero0.setForeground(new java.awt.Color(0, 0, 0));
        jb_numero0.setText("0");
        jb_numero0.setBorder(null);
        jb_numero0.setBorderPainted(false);
        jb_numero0.setContentAreaFilled(false);
        jb_numero0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb_numero0.setFocusPainted(false);
        jb_numero0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jp_numero0.add(jb_numero0);
        jb_numero0.setBounds(0, 0, 110, 50);

        jp_numeros.add(jp_numero0, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 110, 50));

        jp_numero9.setBackground(new java.awt.Color(242, 238, 228));
        jp_numero9.setRoundBottomLeft(20);
        jp_numero9.setRoundBottomRight(20);
        jp_numero9.setRoundTopLeft(20);
        jp_numero9.setRoundTopRight(20);
        jp_numero9.setLayout(null);

        jb_numero9.setBackground(new java.awt.Color(242, 238, 228));
        jb_numero9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jb_numero9.setForeground(new java.awt.Color(0, 0, 0));
        jb_numero9.setText("9");
        jb_numero9.setBorder(null);
        jb_numero9.setBorderPainted(false);
        jb_numero9.setContentAreaFilled(false);
        jb_numero9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb_numero9.setFocusPainted(false);
        jb_numero9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jp_numero9.add(jb_numero9);
        jb_numero9.setBounds(0, 0, 110, 50);

        jp_numeros.add(jp_numero9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 110, 50));

        jp_numero8.setBackground(new java.awt.Color(242, 238, 228));
        jp_numero8.setRoundBottomLeft(20);
        jp_numero8.setRoundBottomRight(20);
        jp_numero8.setRoundTopLeft(20);
        jp_numero8.setRoundTopRight(20);
        jp_numero8.setLayout(null);

        jb_numero8.setBackground(new java.awt.Color(242, 238, 228));
        jb_numero8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jb_numero8.setForeground(new java.awt.Color(0, 0, 0));
        jb_numero8.setText("8");
        jb_numero8.setBorder(null);
        jb_numero8.setBorderPainted(false);
        jb_numero8.setContentAreaFilled(false);
        jb_numero8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb_numero8.setFocusPainted(false);
        jb_numero8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jp_numero8.add(jb_numero8);
        jb_numero8.setBounds(0, 0, 110, 50);

        jp_numeros.add(jp_numero8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 110, 50));

        jp_numero7.setBackground(new java.awt.Color(242, 238, 228));
        jp_numero7.setRoundBottomLeft(20);
        jp_numero7.setRoundBottomRight(20);
        jp_numero7.setRoundTopLeft(20);
        jp_numero7.setRoundTopRight(20);
        jp_numero7.setLayout(null);

        jb_numero7.setBackground(new java.awt.Color(242, 238, 228));
        jb_numero7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jb_numero7.setForeground(new java.awt.Color(0, 0, 0));
        jb_numero7.setText("7");
        jb_numero7.setBorder(null);
        jb_numero7.setBorderPainted(false);
        jb_numero7.setContentAreaFilled(false);
        jb_numero7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb_numero7.setFocusPainted(false);
        jb_numero7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jp_numero7.add(jb_numero7);
        jb_numero7.setBounds(0, 0, 110, 50);

        jp_numeros.add(jp_numero7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 110, 50));

        jp_numero6.setBackground(new java.awt.Color(242, 238, 228));
        jp_numero6.setRoundBottomLeft(20);
        jp_numero6.setRoundBottomRight(20);
        jp_numero6.setRoundTopLeft(20);
        jp_numero6.setRoundTopRight(20);
        jp_numero6.setLayout(null);

        jb_numero6.setBackground(new java.awt.Color(242, 238, 228));
        jb_numero6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jb_numero6.setForeground(new java.awt.Color(0, 0, 0));
        jb_numero6.setText("6");
        jb_numero6.setBorder(null);
        jb_numero6.setBorderPainted(false);
        jb_numero6.setContentAreaFilled(false);
        jb_numero6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb_numero6.setFocusPainted(false);
        jb_numero6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jp_numero6.add(jb_numero6);
        jb_numero6.setBounds(0, 0, 110, 50);

        jp_numeros.add(jp_numero6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 110, 50));

        jp_numero5.setBackground(new java.awt.Color(242, 238, 228));
        jp_numero5.setRoundBottomLeft(20);
        jp_numero5.setRoundBottomRight(20);
        jp_numero5.setRoundTopLeft(20);
        jp_numero5.setRoundTopRight(20);
        jp_numero5.setLayout(null);

        jb_numero5.setBackground(new java.awt.Color(242, 238, 228));
        jb_numero5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jb_numero5.setForeground(new java.awt.Color(0, 0, 0));
        jb_numero5.setText("5");
        jb_numero5.setBorder(null);
        jb_numero5.setBorderPainted(false);
        jb_numero5.setContentAreaFilled(false);
        jb_numero5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb_numero5.setFocusPainted(false);
        jb_numero5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jp_numero5.add(jb_numero5);
        jb_numero5.setBounds(0, 0, 110, 50);

        jp_numeros.add(jp_numero5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 110, 50));

        jp_numero4.setBackground(new java.awt.Color(242, 238, 228));
        jp_numero4.setRoundBottomLeft(20);
        jp_numero4.setRoundBottomRight(20);
        jp_numero4.setRoundTopLeft(20);
        jp_numero4.setRoundTopRight(20);
        jp_numero4.setLayout(null);

        jb_numero4.setBackground(new java.awt.Color(242, 238, 228));
        jb_numero4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jb_numero4.setForeground(new java.awt.Color(0, 0, 0));
        jb_numero4.setText("4");
        jb_numero4.setBorder(null);
        jb_numero4.setBorderPainted(false);
        jb_numero4.setContentAreaFilled(false);
        jb_numero4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb_numero4.setFocusPainted(false);
        jb_numero4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jp_numero4.add(jb_numero4);
        jb_numero4.setBounds(0, 0, 110, 50);

        jp_numeros.add(jp_numero4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 110, 50));

        jp_numero3.setBackground(new java.awt.Color(242, 238, 228));
        jp_numero3.setRoundBottomLeft(20);
        jp_numero3.setRoundBottomRight(20);
        jp_numero3.setRoundTopLeft(20);
        jp_numero3.setRoundTopRight(20);
        jp_numero3.setLayout(null);

        jb_numero3.setBackground(new java.awt.Color(242, 238, 228));
        jb_numero3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jb_numero3.setForeground(new java.awt.Color(0, 0, 0));
        jb_numero3.setText("3");
        jb_numero3.setBorder(null);
        jb_numero3.setBorderPainted(false);
        jb_numero3.setContentAreaFilled(false);
        jb_numero3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb_numero3.setFocusPainted(false);
        jb_numero3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jp_numero3.add(jb_numero3);
        jb_numero3.setBounds(0, 0, 110, 50);

        jp_numeros.add(jp_numero3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 110, 50));

        jp_numero2.setBackground(new java.awt.Color(242, 238, 228));
        jp_numero2.setRoundBottomLeft(20);
        jp_numero2.setRoundBottomRight(20);
        jp_numero2.setRoundTopLeft(20);
        jp_numero2.setRoundTopRight(20);
        jp_numero2.setLayout(null);

        jb_numero2.setBackground(new java.awt.Color(242, 238, 228));
        jb_numero2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jb_numero2.setForeground(new java.awt.Color(0, 0, 0));
        jb_numero2.setText("2");
        jb_numero2.setBorder(null);
        jb_numero2.setBorderPainted(false);
        jb_numero2.setContentAreaFilled(false);
        jb_numero2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb_numero2.setFocusPainted(false);
        jb_numero2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jp_numero2.add(jb_numero2);
        jb_numero2.setBounds(0, 0, 110, 50);

        jp_numeros.add(jp_numero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 110, 50));

        jp_numero1.setBackground(new java.awt.Color(242, 238, 228));
        jp_numero1.setRoundBottomLeft(20);
        jp_numero1.setRoundBottomRight(20);
        jp_numero1.setRoundTopLeft(20);
        jp_numero1.setRoundTopRight(20);
        jp_numero1.setLayout(null);

        jb_numero1.setBackground(new java.awt.Color(242, 238, 228));
        jb_numero1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jb_numero1.setForeground(new java.awt.Color(0, 0, 0));
        jb_numero1.setText("1");
        jb_numero1.setBorder(null);
        jb_numero1.setBorderPainted(false);
        jb_numero1.setContentAreaFilled(false);
        jb_numero1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb_numero1.setFocusPainted(false);
        jb_numero1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jp_numero1.add(jb_numero1);
        jb_numero1.setBounds(0, 0, 110, 50);

        jp_numeros.add(jp_numero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 50));

        jp_ultima_capa.add(jp_numeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 390, 290));

        jp_pedir_dni.setBackground(new java.awt.Color(208, 29, 20));
        jp_pedir_dni.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jp_fondo_numeroDNI.setBackground(new java.awt.Color(242, 238, 228));
        jp_fondo_numeroDNI.setRoundBottomLeft(20);
        jp_fondo_numeroDNI.setRoundBottomRight(20);
        jp_fondo_numeroDNI.setRoundTopLeft(20);
        jp_fondo_numeroDNI.setRoundTopRight(20);
        jp_fondo_numeroDNI.setLayout(null);

        txtNumeroDNI.setBackground(new java.awt.Color(242, 238, 228));
        txtNumeroDNI.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNumeroDNI.setForeground(new java.awt.Color(0, 0, 0));
        txtNumeroDNI.setBorder(null);
        txtNumeroDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroDNIActionPerformed(evt);
            }
        });
        jp_fondo_numeroDNI.add(txtNumeroDNI);
        txtNumeroDNI.setBounds(20, 0, 240, 50);

        jp_pedir_dni.add(jp_fondo_numeroDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 270, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(242, 238, 228));
        jLabel3.setText("Nro de DNI:");
        jp_pedir_dni.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(242, 238, 228));
        jLabel4.setText("Boleta");
        jp_pedir_dni.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jp_ultima_capa.add(jp_pedir_dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 410, 150));

        jp_pedir_ruc.setBackground(new java.awt.Color(208, 29, 20));
        jp_pedir_ruc.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jp_fondo_numeroRUC.setBackground(new java.awt.Color(242, 238, 228));
        jp_fondo_numeroRUC.setRoundBottomLeft(20);
        jp_fondo_numeroRUC.setRoundBottomRight(20);
        jp_fondo_numeroRUC.setRoundTopLeft(20);
        jp_fondo_numeroRUC.setRoundTopRight(20);
        jp_fondo_numeroRUC.setLayout(null);

        txtNumeroRUC.setBackground(new java.awt.Color(242, 238, 228));
        txtNumeroRUC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNumeroRUC.setForeground(new java.awt.Color(0, 0, 0));
        txtNumeroRUC.setBorder(null);
        jp_fondo_numeroRUC.add(txtNumeroRUC);
        txtNumeroRUC.setBounds(20, 0, 240, 50);

        jp_pedir_ruc.add(jp_fondo_numeroRUC, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 270, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 238, 228));
        jLabel1.setText("Nro de RUC:");
        jp_pedir_ruc.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(242, 238, 228));
        jLabel2.setText("Factura");
        jp_pedir_ruc.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jp_ultima_capa.add(jp_pedir_ruc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 410, 160));

        jp_boleta_factura.setBackground(new java.awt.Color(208, 29, 20));
        jp_boleta_factura.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jp_boleta.setBackground(new java.awt.Color(242, 238, 228));
        jp_boleta.setRoundBottomLeft(20);
        jp_boleta.setRoundBottomRight(20);
        jp_boleta.setRoundTopLeft(20);
        jp_boleta.setRoundTopRight(20);
        jp_boleta.setLayout(null);

        jb_boleta.setBackground(new java.awt.Color(242, 238, 228));
        jb_boleta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jb_boleta.setForeground(new java.awt.Color(0, 0, 0));
        jb_boleta.setText("Boleta");
        jb_boleta.setBorder(null);
        jb_boleta.setBorderPainted(false);
        jb_boleta.setContentAreaFilled(false);
        jb_boleta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb_boleta.setFocusPainted(false);
        jb_boleta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jb_boleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_boletaActionPerformed(evt);
            }
        });
        jp_boleta.add(jb_boleta);
        jb_boleta.setBounds(0, 0, 230, 50);

        jp_boleta_factura.add(jp_boleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 230, 50));

        jp_factura.setBackground(new java.awt.Color(242, 238, 228));
        jp_factura.setRoundBottomLeft(20);
        jp_factura.setRoundBottomRight(20);
        jp_factura.setRoundTopLeft(20);
        jp_factura.setRoundTopRight(20);
        jp_factura.setLayout(null);

        jb_factura.setBackground(new java.awt.Color(242, 238, 228));
        jb_factura.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jb_factura.setForeground(new java.awt.Color(0, 0, 0));
        jb_factura.setText("Factura");
        jb_factura.setBorder(null);
        jb_factura.setBorderPainted(false);
        jb_factura.setContentAreaFilled(false);
        jb_factura.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb_factura.setFocusPainted(false);
        jb_factura.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jb_factura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_facturaActionPerformed(evt);
            }
        });
        jp_factura.add(jb_factura);
        jb_factura.setBounds(0, 0, 230, 50);

        jp_boleta_factura.add(jp_factura, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 230, 50));

        jp_ultima_capa.add(jp_boleta_factura, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 410, 450));

        jp_mensaje_tarjeta.setBackground(new java.awt.Color(208, 29, 20));
        jp_mensaje_tarjeta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(242, 238, 228));
        jLabel5.setText("tarjeta al lector");
        jp_mensaje_tarjeta.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(242, 238, 228));
        jLabel6.setText("Por favor, acerque su");
        jp_mensaje_tarjeta.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        jl_pos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imgPOS150x150.png"))); // NOI18N
        jp_mensaje_tarjeta.add(jl_pos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 150, 170));

        jp_ultima_capa.add(jp_mensaje_tarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 410, 450));

        jp_mensaje_billetera_digital.setBackground(new java.awt.Color(208, 29, 20));
        jp_mensaje_billetera_digital.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(242, 238, 228));
        jLabel7.setText("para realizar el pago");
        jp_mensaje_billetera_digital.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 70, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(242, 238, 228));
        jLabel8.setText("Escanea el codigo QR");
        jp_mensaje_billetera_digital.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        jl_pos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/QRyape140x142.jpg"))); // NOI18N
        jp_mensaje_billetera_digital.add(jl_pos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 140, 140, 140));

        jp_ultima_capa.add(jp_mensaje_billetera_digital, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 410, 450));

        jp_mensaje_confirmacion.setBackground(new java.awt.Color(208, 29, 20));
        jp_mensaje_confirmacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(242, 238, 228));
        jLabel9.setText("éxito");
        jp_mensaje_confirmacion.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 70, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(242, 238, 228));
        jLabel10.setText("en PizzaLab");
        jp_mensaje_confirmacion.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, -1, -1));

        jl_pos2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/checkGrande150x150.png"))); // NOI18N
        jp_mensaje_confirmacion.add(jl_pos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 130, 150, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(242, 238, 228));
        jLabel11.setText("Pago realizado con");
        jp_mensaje_confirmacion.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(242, 238, 228));
        jLabel12.setText("Gracias por comprar");
        jp_mensaje_confirmacion.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 330, -1, -1));

        jp_ultima_capa.add(jp_mensaje_confirmacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 410, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jp_ultima_capa, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jp_ultima_capa, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_boletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_boletaActionPerformed
        // Poner boleta como verdadero
        this.boleta = true;

        // Ocultar eleccion boleta / factura
        jp_boleta_factura.setVisible(false);
        jp_pedir_ruc.setVisible(false);
        
        // Mostrar siguiente
        jp_pedir_dni.setVisible(true);
        jp_numeros.setVisible(true);
    }//GEN-LAST:event_jb_boletaActionPerformed

    private void jb_facturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_facturaActionPerformed
        // Poner factura como verdadero
        this.factura = true;
        
        // Ocultar eleccion boleta / factura
        jp_boleta_factura.setVisible(false);
        jp_pedir_dni.setVisible(false);
        
        // Mostrar siguiente
        jp_pedir_ruc.setVisible(true);
        jp_numeros.setVisible(true);
    }//GEN-LAST:event_jb_facturaActionPerformed

    // Nuevo método para agregar dígito según campo activo y límite
    private void agregarDigitoCampoActivo(String digito) {
        if (boleta) {
            String text = txtNumeroDNI.getText();
            if (text.length() < 8 && digito.matches("\\d")) {
                txtNumeroDNI.setText(text + digito);
            }
        } else if (factura) {
            String text = txtNumeroRUC.getText();
            if (text.length() < 11 && digito.matches("\\d")) {
                txtNumeroRUC.setText(text + digito);
            }
        }
    }

    private void jb_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_eliminarActionPerformed
        if (boleta) {
            String d = txtNumeroDNI.getText();
            if (!d.isEmpty()) {
                txtNumeroDNI.setText(d.substring(0, d.length() - 1));
            }
        } else if (factura) {
            String t = txtNumeroRUC.getText();
            if (!t.isEmpty()) {
                txtNumeroRUC.setText(t.substring(0, t.length() - 1));
            }
        }
    }//GEN-LAST:event_jb_eliminarActionPerformed

    private void jb_confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_confirmarActionPerformed
        // 1. Leer y “limpiar” el texto
        String numRuc = txtNumeroRUC.getText().trim();
        String numDNI = txtNumeroDNI.getText().trim();

        // Validación de DNI
        if (boleta) {
            if (!numDNI.matches("\\d{8}")) {
                javax.swing.JOptionPane.showMessageDialog(this, "El DNI debe tener exactamente 8 dígitos.");
                txtNumeroDNI.setText("");
                return;
            }
        }
        // Validación de RUC
        if (factura) {
            if (!numRuc.matches("(10|20)\\d{9}")) {
                javax.swing.JOptionPane.showMessageDialog(this, "El RUC debe tener 11 dígitos y empezar con 10 o 20.");
                txtNumeroRUC.setText("");
                return;
            }
        }
        // Ocultar la ventana actual
        jp_pedir_dni.setVisible(false);
        jp_pedir_ruc.setVisible(false);
        jp_numeros.setVisible(false);
        jp_boleta_factura.setVisible(false);
        
        String metodoPago = controlador != null ? controlador.getMetodoPago() : null;
        if ("BILLETERA".equals(metodoPago)) {
            jp_mensaje_billetera_digital.setVisible(true);
        } else if ("TARJETA".equals(metodoPago)) {
            jp_mensaje_tarjeta.setVisible(true);
        } else {
            System.out.println("Error: método de pago no seleccionado.");
            return;
        }
                
        new javax.swing.Timer(5000, e1 -> {
            if("BILLETERA".equals(metodoPago)){
                jp_mensaje_billetera_digital.setVisible(false);
            } else if ("TARJETA".equals(metodoPago)) {
                jp_mensaje_tarjeta.setVisible(false);
            } else {
                System.out.println("Error: método de pago no seleccionado.");
                return;
            }
            // Mostrar ventana de confirmacion de pago
            jp_mensaje_confirmacion.setVisible(true);
            new javax.swing.Timer(5000, e2 -> {
                jp_mensaje_confirmacion.setVisible(false);
                // Ocultar apartados
                jp_pedir_ruc.setVisible(false);
                jp_pedir_dni.setVisible(false);
                jp_numeros.setVisible(false);
                jp_mensaje_tarjeta.setVisible(false);
                jp_mensaje_billetera_digital.setVisible(false);
                jp_mensaje_confirmacion.setVisible(false);
                // Cerrar el actual JFrame
                ProcesoPagoVista.this.dispose();
                // Guardar el tipo de comprobante y documento en el controlador y confirmar pedido
                if (controlador != null) {
                    if (boleta) {
                        controlador.seleccionarTipoComprobante("BOLETA");
                        controlador.ingresarDocumento(numDNI);
                    } else if (factura) {
                        controlador.seleccionarTipoComprobante("FACTURA");
                        controlador.ingresarDocumento(numRuc);
                    }
                    controlador.confirmarPedido();
                }
            }) {{ setRepeats(false); }}.start();
        }) {{ setRepeats(false); }}.start();
    }//GEN-LAST:event_jb_confirmarActionPerformed

    private void txtNumeroDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroDNIActionPerformed

    private void jb_numero7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_numero7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_numero7ActionPerformed

    private void jb_numero6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_numero6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_numero6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jb_boleta;
    private javax.swing.JButton jb_confirmar;
    private javax.swing.JButton jb_eliminar;
    private javax.swing.JButton jb_factura;
    private javax.swing.JButton jb_numero0;
    private javax.swing.JButton jb_numero1;
    private javax.swing.JButton jb_numero2;
    private javax.swing.JButton jb_numero3;
    private javax.swing.JButton jb_numero4;
    private javax.swing.JButton jb_numero5;
    private javax.swing.JButton jb_numero6;
    private javax.swing.JButton jb_numero7;
    private javax.swing.JButton jb_numero8;
    private javax.swing.JButton jb_numero9;
    private javax.swing.JLabel jl_logo_empresa;
    private javax.swing.JLabel jl_pos;
    private javax.swing.JLabel jl_pos1;
    private javax.swing.JLabel jl_pos2;
    private MyContainers.PanelRound jp_boleta;
    private javax.swing.JPanel jp_boleta_factura;
    private MyContainers.PanelRound jp_confirmar;
    private MyContainers.PanelRound jp_eliminar;
    private MyContainers.PanelRound jp_factura;
    private MyContainers.PanelRound jp_fondo_numeroDNI;
    private MyContainers.PanelRound jp_fondo_numeroRUC;
    private javax.swing.JPanel jp_mensaje_billetera_digital;
    private javax.swing.JPanel jp_mensaje_confirmacion;
    private javax.swing.JPanel jp_mensaje_tarjeta;
    private MyContainers.PanelRound jp_numero0;
    private MyContainers.PanelRound jp_numero1;
    private MyContainers.PanelRound jp_numero2;
    private MyContainers.PanelRound jp_numero3;
    private MyContainers.PanelRound jp_numero4;
    private MyContainers.PanelRound jp_numero5;
    private MyContainers.PanelRound jp_numero6;
    private MyContainers.PanelRound jp_numero7;
    private MyContainers.PanelRound jp_numero8;
    private MyContainers.PanelRound jp_numero9;
    private javax.swing.JPanel jp_numeros;
    private javax.swing.JPanel jp_pedir_dni;
    private javax.swing.JPanel jp_pedir_ruc;
    private javax.swing.JPanel jp_ultima_capa;
    private javax.swing.JTextField txtNumeroDNI;
    private javax.swing.JTextField txtNumeroRUC;
    // End of variables declaration//GEN-END:variables
}
