package vista;

import controlador.PedidoControlador;

public class TipoConsumoPagoVista extends javax.swing.JFrame {
    private PedidoControlador controlador;  // importar controlador
    private InicioVista inicioVista;

    public void setControlador(PedidoControlador ctrl) {
        this.controlador = ctrl;
    }
    
    public void setInicioVista(InicioVista vista) {
        this.inicioVista = vista;
    }

    public TipoConsumoPagoVista() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.fondoBilleteraDigital.setVisible(false);
        this.fondoTarjeta.setVisible(false);
        this.jl_pregunta_pago.setVisible(false);
        this.jb_comer_aqui.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_ultima_capa = new javax.swing.JPanel();
        jl_logo_empresa = new javax.swing.JLabel();
        jl_pregunta_consumo = new javax.swing.JLabel();
        jl_pregunta_pago = new javax.swing.JLabel();
        fondoComerAqui = new MyContainers.PanelRound();
        jb_comer_aqui = new javax.swing.JButton("<html><u>Texto Subrayado</u></html>");
        jl_titulo_comer_aqui = new javax.swing.JLabel();
        fondoParaLlevar = new MyContainers.PanelRound();
        jb_para_llevar = new javax.swing.JButton("<html><u>Texto Subrayado</u></html>");
        jl_titulo_para_llevar = new javax.swing.JLabel();
        fondoBilleteraDigital = new MyContainers.PanelRound();
        jl_logos_digitales = new javax.swing.JLabel();
        jl_aceptamos1 = new javax.swing.JLabel();
        jl_titulo_billetera_digital1 = new javax.swing.JLabel();
        jl_titulo_billetera_digital = new javax.swing.JLabel();
        jb_billetera_digital = new javax.swing.JButton("<html><u>Texto Subrayado</u></html>");
        fondoTarjeta = new MyContainers.PanelRound();
        jl_logos_tarjetas = new javax.swing.JLabel();
        jl_aceptamos = new javax.swing.JLabel();
        jb_tarjeta = new javax.swing.JButton("<html><u>Texto Subrayado</u></html>");
        jl_titulo_tarjeta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jp_ultima_capa.setBackground(new java.awt.Color(208, 29, 20));
        jp_ultima_capa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_logo_empresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoPizzaLabGrande200x200.png"))); // NOI18N
        jp_ultima_capa.add(jl_logo_empresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 190, 170));

        jl_pregunta_consumo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jl_pregunta_consumo.setForeground(new java.awt.Color(242, 238, 228));
        jl_pregunta_consumo.setText("¿Dónde comerás?");
        jp_ultima_capa.add(jl_pregunta_consumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, -1, -1));

        jl_pregunta_pago.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jl_pregunta_pago.setForeground(new java.awt.Color(242, 238, 228));
        jl_pregunta_pago.setText("¿Como te gustaría pagar?");
        jp_ultima_capa.add(jl_pregunta_pago, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));

        fondoComerAqui.setBackground(new java.awt.Color(242, 238, 228));
        fondoComerAqui.setRoundBottomLeft(20);
        fondoComerAqui.setRoundBottomRight(20);
        fondoComerAqui.setRoundTopLeft(20);
        fondoComerAqui.setRoundTopRight(20);
        fondoComerAqui.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_comer_aqui.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jb_comer_aqui.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ComerAqui90x90.png"))); // NOI18N
        jb_comer_aqui.setText("");
        jb_comer_aqui.setToolTipText("");
        jb_comer_aqui.setBorder(null);
        jb_comer_aqui.setBorderPainted(false);
        jb_comer_aqui.setContentAreaFilled(false);
        jb_comer_aqui.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb_comer_aqui.setFocusPainted(false);
        jb_comer_aqui.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jb_comer_aqui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_comer_aquiActionPerformed(evt);
            }
        });
        fondoComerAqui.add(jb_comer_aqui, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 130, 160));

        jl_titulo_comer_aqui.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jl_titulo_comer_aqui.setForeground(new java.awt.Color(0, 0, 0));
        jl_titulo_comer_aqui.setText("Comer aquí");
        fondoComerAqui.add(jl_titulo_comer_aqui, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 10, 100, 40));

        jp_ultima_capa.add(fondoComerAqui, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 130, 180));

        fondoParaLlevar.setBackground(new java.awt.Color(242, 238, 228));
        fondoParaLlevar.setRoundBottomLeft(20);
        fondoParaLlevar.setRoundBottomRight(20);
        fondoParaLlevar.setRoundTopLeft(20);
        fondoParaLlevar.setRoundTopRight(20);
        fondoParaLlevar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_para_llevar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jb_para_llevar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ParaLlevar90x63.png"))); // NOI18N
        jb_para_llevar.setText("");
        jb_para_llevar.setBorder(null);
        jb_para_llevar.setBorderPainted(false);
        jb_para_llevar.setContentAreaFilled(false);
        jb_para_llevar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb_para_llevar.setFocusPainted(false);
        jb_para_llevar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jb_para_llevar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_para_llevarActionPerformed(evt);
            }
        });
        fondoParaLlevar.add(jb_para_llevar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 130, 150));

        jl_titulo_para_llevar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jl_titulo_para_llevar.setForeground(new java.awt.Color(0, 0, 0));
        jl_titulo_para_llevar.setText("Para llevar");
        fondoParaLlevar.add(jl_titulo_para_llevar, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 10, 90, 40));

        jp_ultima_capa.add(fondoParaLlevar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 130, 180));

        fondoBilleteraDigital.setBackground(new java.awt.Color(242, 238, 228));
        fondoBilleteraDigital.setRoundBottomLeft(20);
        fondoBilleteraDigital.setRoundBottomRight(20);
        fondoBilleteraDigital.setRoundTopLeft(20);
        fondoBilleteraDigital.setRoundTopRight(20);
        fondoBilleteraDigital.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_logos_digitales.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jl_logos_digitales.setForeground(new java.awt.Color(0, 0, 0));
        jl_logos_digitales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/yapePlin55x25.png"))); // NOI18N
        fondoBilleteraDigital.add(jl_logos_digitales, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 133, -1, 40));

        jl_aceptamos1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jl_aceptamos1.setForeground(new java.awt.Color(0, 0, 0));
        jl_aceptamos1.setText("Aceptamos:");
        fondoBilleteraDigital.add(jl_aceptamos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 60, 20));

        jl_titulo_billetera_digital1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jl_titulo_billetera_digital1.setForeground(new java.awt.Color(0, 0, 0));
        jl_titulo_billetera_digital1.setText("Digital");
        fondoBilleteraDigital.add(jl_titulo_billetera_digital1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 28, -1, 40));

        jl_titulo_billetera_digital.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jl_titulo_billetera_digital.setForeground(new java.awt.Color(0, 0, 0));
        jl_titulo_billetera_digital.setText("Billetera");
        fondoBilleteraDigital.add(jl_titulo_billetera_digital, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 5, -1, 40));

        jb_billetera_digital.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jb_billetera_digital.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/PosQR50x50.png"))); // NOI18N
        jb_billetera_digital.setText("");
        jb_billetera_digital.setBorder(null);
        jb_billetera_digital.setBorderPainted(false);
        jb_billetera_digital.setContentAreaFilled(false);
        jb_billetera_digital.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb_billetera_digital.setFocusPainted(false);
        jb_billetera_digital.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jb_billetera_digital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_billetera_digitalActionPerformed(evt);
            }
        });
        fondoBilleteraDigital.add(jb_billetera_digital, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 130, 180));

        jp_ultima_capa.add(fondoBilleteraDigital, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 130, 180));

        fondoTarjeta.setBackground(new java.awt.Color(242, 238, 228));
        fondoTarjeta.setRoundBottomLeft(20);
        fondoTarjeta.setRoundBottomRight(20);
        fondoTarjeta.setRoundTopLeft(20);
        fondoTarjeta.setRoundTopRight(20);
        fondoTarjeta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_logos_tarjetas.setForeground(new java.awt.Color(0, 0, 0));
        jl_logos_tarjetas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogosTarjetas50x23.png"))); // NOI18N
        fondoTarjeta.add(jl_logos_tarjetas, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 130, 60, 40));

        jl_aceptamos.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jl_aceptamos.setForeground(new java.awt.Color(0, 0, 0));
        jl_aceptamos.setText("Aceptamos:");
        fondoTarjeta.add(jl_aceptamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 105, 60, 20));

        jb_tarjeta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jb_tarjeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Tarjeta50x50.png"))); // NOI18N
        jb_tarjeta.setText("");
        jb_tarjeta.setBorder(null);
        jb_tarjeta.setBorderPainted(false);
        jb_tarjeta.setContentAreaFilled(false);
        jb_tarjeta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb_tarjeta.setFocusPainted(false);
        jb_tarjeta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jb_tarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_tarjetaActionPerformed(evt);
            }
        });
        fondoTarjeta.add(jb_tarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 150));

        jl_titulo_tarjeta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jl_titulo_tarjeta.setForeground(new java.awt.Color(0, 0, 0));
        jl_titulo_tarjeta.setText("Tarjeta");
        fondoTarjeta.add(jl_titulo_tarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 10, 60, 40));

        jp_ultima_capa.add(fondoTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 130, 180));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jp_ultima_capa, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jp_ultima_capa, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_comer_aquiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_comer_aquiActionPerformed
        // LOGICA PARA GUARDAR LA ELECCION DE TIPOCONSUMO
        controlador.seleccionarTipoConsumo("LOCAL");

        // Quitar la visibilidad del apartado tipoConsumo
        this.fondoComerAqui.setVisible(false);
        this.fondoParaLlevar.setVisible(false);
        this.jl_pregunta_consumo.setVisible(false);
        
        // Hacer visible el siguiente apartado tipoPago
        this.fondoBilleteraDigital.setVisible(true);
        this.fondoTarjeta.setVisible(true);
        this.jl_pregunta_pago.setVisible(true);
    }//GEN-LAST:event_jb_comer_aquiActionPerformed

    private void jb_tarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_tarjetaActionPerformed
        if (controlador != null && inicioVista != null) {
            controlador.seleccionarMetodoPago("TARJETA");
            inicioVista.setVisible(true);
            this.setVisible(false);
        } else {
            System.err.println("Error: controlador o inicioVista no asignados.");
        }
    }//GEN-LAST:event_jb_tarjetaActionPerformed

    private void jb_billetera_digitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_billetera_digitalActionPerformed
        if (controlador != null && inicioVista != null) {
            controlador.seleccionarMetodoPago("BILLETERA");
            inicioVista.setVisible(true);
            this.setVisible(false);
        } else {
            System.err.println("Error: controlador o inicioVista no asignados.");
        }
    }//GEN-LAST:event_jb_billetera_digitalActionPerformed

    private void jb_para_llevarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_para_llevarActionPerformed
        // LOGICA PARA GUARDAR LA ELECCION DE TIPOCONSUMO
        controlador.seleccionarTipoConsumo("LLEVAR");

        // Quitar la visibilidad del apartado tipoConsumo
        this.fondoComerAqui.setVisible(false);
        this.fondoParaLlevar.setVisible(false);
        this.jl_pregunta_consumo.setVisible(false);
        
        // Hacer visible el siguiente apartado tipoPago
        this.fondoBilleteraDigital.setVisible(true);
        this.fondoTarjeta.setVisible(true);
        this.jl_pregunta_pago.setVisible(true);
    }//GEN-LAST:event_jb_para_llevarActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private MyContainers.PanelRound fondoBilleteraDigital;
    private MyContainers.PanelRound fondoComerAqui;
    private MyContainers.PanelRound fondoParaLlevar;
    private MyContainers.PanelRound fondoTarjeta;
    private javax.swing.JButton jb_billetera_digital;
    private javax.swing.JButton jb_comer_aqui;
    private javax.swing.JButton jb_para_llevar;
    private javax.swing.JButton jb_tarjeta;
    private javax.swing.JLabel jl_aceptamos;
    private javax.swing.JLabel jl_aceptamos1;
    private javax.swing.JLabel jl_logo_empresa;
    private javax.swing.JLabel jl_logos_digitales;
    private javax.swing.JLabel jl_logos_tarjetas;
    private javax.swing.JLabel jl_pregunta_consumo;
    private javax.swing.JLabel jl_pregunta_pago;
    private javax.swing.JLabel jl_titulo_billetera_digital;
    private javax.swing.JLabel jl_titulo_billetera_digital1;
    private javax.swing.JLabel jl_titulo_comer_aqui;
    private javax.swing.JLabel jl_titulo_para_llevar;
    private javax.swing.JLabel jl_titulo_tarjeta;
    private javax.swing.JPanel jp_ultima_capa;
    // End of variables declaration//GEN-END:variables
}
